language: java


dist: trusty

jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "lucaserlacher-github"
    token:
      secure: $sonnar_key
      
deploy:
 provider: heroku
 api_key:
  secure: $heroku_key
 app:
  master: amaproject
 on: master

before_install:
  - sudo apt-get install -y jq

script:  
  - mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar > sonar.txt
  - sh breakingbuildsonar.sh sonar.txt $sonnar_key https://sonarcloud.io
  - rm sonar.txt

notifications:
 slack: bsi-ifserra:RCNpHRd9ys5acaqRPaFcNjVL
