language: java

sudo: enable

dist: trusty

jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "lucaserlacher-github"
    token:
      secure: $sonnar_key

before_install:
  - sudo apt-get install -y jq


script:  
  - mvn test
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar > sonar.txt
  - sh breakingbuildsonar.sh sonar.txt $sonnar_key https://sonarcloud.io
  - rm sonar.txt

branches:
  only:
    - master
    - devTarcisio
    - devCaio
    - devLucas

notifications:
  slack: bsi-ifserra:RCNpHRd9ys5acaqRPaFcNjVL

