language: java
dist: trusty
jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "lucaserlacher-github"
    token:
      secure: $sonnar_key

script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - cd Interface
  - mvn install

notifications:
  slack: bsi-ifserra:RCNpHRd9ys5acaqRPaFcNjVL
