language: java
dist: trusty
jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "lucaserlacher-github"
    token:
      secure: $sonnar_key
      
deploy:
 provider: heroku
 api_key:
  secure: $heroku_key
 app:
  master: amaproject
 on: devTarcisio

script:  
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - cd Interface
  - mvn install

notifications:
  slack: bsi-ifserra:RCNpHRd9ys5acaqRPaFcNjVL

