language: java

jdk:
 - oraclejdk8
 
 addons:
  sonarcloud:
    organization: "lucaserlacher-github"
    token:
      secure: "b2e05f503b530adf0b8c9a868b9ec75d4d091487"

branches:
  only:
    - master
    - dev
    - devTarcisio
    - devLucas

notifications:
  slack: bsi-ifserra:RCNpHRd9ys5acaqRPaFcNjVL

script:
  - sonar-scanner
