/* ModeloLogicoAMA: */

CREATE TABLE ENDEREcO (
    CEP int not null,
    IDENDERECO int PRIMARY KEY,
    NOME varchar(50) not null,
    IDBAIRRO int ,
    IDLOGRADOURO int
);

CREATE TABLE BAIRRO (
    IDBAIRRO int PRIMARY KEY,
    NOME varchar(50) not null,
    IDCIDADE int
);

CREATE TABLE LOGRADOURO (
    NOME varchar(50) not null,
    IDLOGRADOURO int PRIMARY KEY
);

CREATE TABLE CIDADE (
    IDCIDADE int PRIMARY KEY,
    NOME varchar(50) not null,
    IDESTADO int not null
);

CREATE TABLE ESTADO (
    IDESTADO int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE SEXO (
    NOME varchar(50) not null,
    IDSEXO int PRIMARY KEY
);

CREATE TABLE PESSOA (
    IDPESSOA int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE CONTATO (
    DESCRICAO varchar(50) not null,
    IDCONTATO int PRIMARY KEY,
    IDOPESSOA int,
    IDTIPOCONTATO int
);

CREATE TABLE TIPOCONTATO (
    IDTIPOCONTATO int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE SERVICO (
    IDSERVICO int PRIMARY KEY,
    HORA time without time zone not null,
    DATA date,
    IDAGENTESAUDE int,
    IDTIPOSERVICO int,
    IDPACIENTE int,
    IDCENTRO int,
    IDSTATUS int
);

CREATE TABLE PLANOSAUDE (
    IDPLANOSAUDE int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE PESSOAFISICA (
    CPF varchar(50) not null,
    DATANASCIMENTO date not null,
    IDPESSOA int,
    IDSEXO int,
    IDCIDADE int,
    IDPESSOAFISICA int PRIMARY KEY,
    LOGIN varchar(50) not null,
    SENHA varchar(50) not null,
    IDTIPOUSUARIO int,
    UNIQUE (CPF, LOGIN)
);

CREATE TABLE CENTRO (
    CNPJ VARCHAR(50) not null,
    IDPESSOA int,
    IDCENTRO int PRIMARY KEY,
    UNIQUE (CNPJ, IDCENTRO)
);

CREATE TABLE AGENTESAUDE (
    IDAGENTESAUDE int PRIMARY KEY,
    INSCRICAO int,
    IDPESSOAFISICA int,
    IDESTADO int,
    IDTIPOREGISTRO int
);

CREATE TABLE TIPOUSUARIO (
    IDTIPOUSUARIO int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE TIPOREGISTRO (
    IDTIPOREGISTRO int PRIMARY KEY,
    DESCRICAO varchar(50) not null
);

CREATE TABLE TIPOSERVICO (
    IDTIPOSERVICO int PRIMARY KEY,
    DESCRICAO varchar(50) not null,
    PRECO float not null
);

CREATE TABLE STATUS (
    IDSTATUS int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE PACIENTE (
    IDPESSOAFISICA int,
    IDPLANOSAUDE int,
    IDPACIENTE int PRIMARY KEY UNIQUE
);

CREATE TABLE HORARIOATENDIMENTO (
    IDHORARIOATENDIMENTO int PRIMARY KEY,
    HORAINICIO time without time zone not null,
    HORAFIM time without time zone not null,
    IDDIASEMANA int,
    IDAGENTE int,
    INTERVALO time without time zone not null
);

CREATE TABLE DIASEMANA (
    IDDIASEMANA int PRIMARY KEY,
    NOME varchar(50) not null
);

CREATE TABLE PESSOA_ENDERECO (
    IDENDERECO int,
    IDPESSOA int
);

CREATE TABLE AGENTESAUDE_CENTRO (
    IDAGENTESAUDE int,
    IDCENTRO int
);

CREATE TABLE CENTRO_SERVICO (
    IDSERVICO int,
    IDCENTRO int
);
 
ALTER TABLE ENDEREcO ADD CONSTRAINT FK_ENDEREcO_1
    FOREIGN KEY (IDBAIRRO)
    REFERENCES BAIRRO (IDBAIRRO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ENDEREcO ADD CONSTRAINT FK_ENDEREcO_2
    FOREIGN KEY (IDLOGRADOURO)
    REFERENCES LOGRADOURO (IDLOGRADOURO)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_1
    FOREIGN KEY (IDCIDADE)
    REFERENCES CIDADE (IDCIDADE)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_1
    FOREIGN KEY (IDESTADO)
    REFERENCES ESTADO (IDESTADO)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_1
    FOREIGN KEY (IDOPESSOA)
    REFERENCES PESSOA (IDPESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_2
    FOREIGN KEY (IDTIPOCONTATO)
    REFERENCES TIPOCONTATO (IDTIPOCONTATO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_1
    FOREIGN KEY (IDAGENTESAUDE)
    REFERENCES AGENTESAUDE (IDAGENTESAUDE);
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_2
    FOREIGN KEY (IDTIPOSERVICO)
    REFERENCES TIPOSERVICO (IDTIPOSERVICO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_3
    FOREIGN KEY (IDPACIENTE)
    REFERENCES PACIENTE (IDPACIENTE);
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_4
    FOREIGN KEY (IDCENTRO)
    REFERENCES CENTRO (IDCENTRO);
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_5
    FOREIGN KEY (IDSTATUS)
    REFERENCES STATUS (IDSTATUS);
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_1
    FOREIGN KEY (IDPESSOA)
    REFERENCES PESSOA (IDPESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_2
    FOREIGN KEY (IDSEXO)
    REFERENCES SEXO (IDSEXO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_3
    FOREIGN KEY (IDCIDADE)
    REFERENCES CIDADE (IDCIDADE)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_4
    FOREIGN KEY (IDTIPOUSUARIO)
    REFERENCES TIPOUSUARIO (IDTIPOUSUARIO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CENTRO ADD CONSTRAINT FK_CENTRO_1
    FOREIGN KEY (IDPESSOA)
    REFERENCES PESSOA (IDPESSOA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE AGENTESAUDE ADD CONSTRAINT FK_AGENTESAUDE_1
    FOREIGN KEY (IDPESSOAFISICA)
    REFERENCES PESSOAFISICA (IDPESSOAFISICA);
 
ALTER TABLE AGENTESAUDE ADD CONSTRAINT FK_AGENTESAUDE_2
    FOREIGN KEY (IDESTADO)
    REFERENCES ESTADO (IDESTADO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE AGENTESAUDE ADD CONSTRAINT FK_AGENTESAUDE_3
    FOREIGN KEY (IDTIPOREGISTRO)
    REFERENCES TIPOREGISTRO (IDTIPOREGISTRO)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_1
    FOREIGN KEY (IDPESSOAFISICA)
    REFERENCES PESSOAFISICA (IDPESSOAFISICA)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PACIENTE ADD CONSTRAINT FK_PACIENTE_2
    FOREIGN KEY (IDPLANOSAUDE)
    REFERENCES PLANOSAUDE (IDPLANOSAUDE)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE HORARIOATENDIMENTO ADD CONSTRAINT FK_HORARIOATENDIMENTO_1
    FOREIGN KEY (IDDIASEMANA)
    REFERENCES DIASEMANA (IDDIASEMANA);
 
ALTER TABLE HORARIOATENDIMENTO ADD CONSTRAINT FK_HORARIOATENDIMENTO_2
    FOREIGN KEY (IDAGENTE)
    REFERENCES AGENTESAUDE (IDAGENTESAUDE);
 
ALTER TABLE PESSOA_ENDERECO ADD CONSTRAINT FK_PESSOA_ENDERECO_0
    FOREIGN KEY (IDENDERECO)
    REFERENCES ENDEREcO (IDENDERECO)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE PESSOA_ENDERECO ADD CONSTRAINT FK_PESSOA_ENDERECO_1
    FOREIGN KEY (IDPESSOA)
    REFERENCES PESSOA (IDPESSOA)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE AGENTESAUDE_CENTRO ADD CONSTRAINT FK_AGENTESAUDE_CENTRO_0
    FOREIGN KEY (IDAGENTESAUDE)
    REFERENCES AGENTESAUDE (IDAGENTESAUDE);
 
ALTER TABLE AGENTESAUDE_CENTRO ADD CONSTRAINT FK_AGENTESAUDE_CENTRO_1
    FOREIGN KEY (IDCENTRO)
    REFERENCES CENTRO (IDCENTRO)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE CENTRO_SERVICO ADD CONSTRAINT FK_CENTRO_SERVICO_0
    FOREIGN KEY (IDSERVICO)
    REFERENCES TIPOSERVICO (IDTIPOSERVICO)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CENTRO_SERVICO ADD CONSTRAINT FK_CENTRO_SERVICO_1
    FOREIGN KEY (IDCENTRO)
    REFERENCES CENTRO (IDCENTRO)
    ON DELETE SET NULL ON UPDATE CASCADE;